/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubesphere.io/kubesphere/pkg/apis/infra/v1alpha1"
	scheme "kubesphere.io/kubesphere/pkg/client/clientset/versioned/scheme"
)

// EdgeClustersGetter has a method to return a EdgeClusterInterface.
// A group's client should implement this interface.
type EdgeClustersGetter interface {
	EdgeClusters(namespace string) EdgeClusterInterface
}

// EdgeClusterInterface has methods to work with EdgeCluster resources.
type EdgeClusterInterface interface {
	Create(ctx context.Context, edgeCluster *v1alpha1.EdgeCluster, opts v1.CreateOptions) (*v1alpha1.EdgeCluster, error)
	Update(ctx context.Context, edgeCluster *v1alpha1.EdgeCluster, opts v1.UpdateOptions) (*v1alpha1.EdgeCluster, error)
	UpdateStatus(ctx context.Context, edgeCluster *v1alpha1.EdgeCluster, opts v1.UpdateOptions) (*v1alpha1.EdgeCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.EdgeCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.EdgeClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EdgeCluster, err error)
	EdgeClusterExpansion
}

// edgeClusters implements EdgeClusterInterface
type edgeClusters struct {
	client rest.Interface
	ns     string
}

// newEdgeClusters returns a EdgeClusters
func newEdgeClusters(c *InfraV1alpha1Client, namespace string) *edgeClusters {
	return &edgeClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the edgeCluster, and returns the corresponding edgeCluster object, and an error if there is any.
func (c *edgeClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.EdgeCluster, err error) {
	result = &v1alpha1.EdgeCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("edgeclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EdgeClusters that match those selectors.
func (c *edgeClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EdgeClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.EdgeClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("edgeclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested edgeClusters.
func (c *edgeClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("edgeclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a edgeCluster and creates it.  Returns the server's representation of the edgeCluster, and an error, if there is any.
func (c *edgeClusters) Create(ctx context.Context, edgeCluster *v1alpha1.EdgeCluster, opts v1.CreateOptions) (result *v1alpha1.EdgeCluster, err error) {
	result = &v1alpha1.EdgeCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("edgeclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(edgeCluster).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a edgeCluster and updates it. Returns the server's representation of the edgeCluster, and an error, if there is any.
func (c *edgeClusters) Update(ctx context.Context, edgeCluster *v1alpha1.EdgeCluster, opts v1.UpdateOptions) (result *v1alpha1.EdgeCluster, err error) {
	result = &v1alpha1.EdgeCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("edgeclusters").
		Name(edgeCluster.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(edgeCluster).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *edgeClusters) UpdateStatus(ctx context.Context, edgeCluster *v1alpha1.EdgeCluster, opts v1.UpdateOptions) (result *v1alpha1.EdgeCluster, err error) {
	result = &v1alpha1.EdgeCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("edgeclusters").
		Name(edgeCluster.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(edgeCluster).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the edgeCluster and deletes it. Returns an error if one occurs.
func (c *edgeClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("edgeclusters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *edgeClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("edgeclusters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched edgeCluster.
func (c *edgeClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EdgeCluster, err error) {
	result = &v1alpha1.EdgeCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("edgeclusters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
