/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/edgewize-io/edgewize/pkg/apis/infra/v1alpha1"
	scheme "github.com/edgewize-io/edgewize/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VClusterNamespacesGetter has a method to return a VClusterNamespaceInterface.
// A group's client should implement this interface.
type VClusterNamespacesGetter interface {
	VClusterNamespaces(namespace string) VClusterNamespaceInterface
}

// VClusterNamespaceInterface has methods to work with VClusterNamespace resources.
type VClusterNamespaceInterface interface {
	Create(ctx context.Context, vClusterNamespace *v1alpha1.VClusterNamespace, opts v1.CreateOptions) (*v1alpha1.VClusterNamespace, error)
	Update(ctx context.Context, vClusterNamespace *v1alpha1.VClusterNamespace, opts v1.UpdateOptions) (*v1alpha1.VClusterNamespace, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VClusterNamespace, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VClusterNamespaceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VClusterNamespace, err error)
	VClusterNamespaceExpansion
}

// vClusterNamespaces implements VClusterNamespaceInterface
type vClusterNamespaces struct {
	client rest.Interface
	ns     string
}

// newVClusterNamespaces returns a VClusterNamespaces
func newVClusterNamespaces(c *InfraV1alpha1Client, namespace string) *vClusterNamespaces {
	return &vClusterNamespaces{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vClusterNamespace, and returns the corresponding vClusterNamespace object, and an error if there is any.
func (c *vClusterNamespaces) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VClusterNamespace, err error) {
	result = &v1alpha1.VClusterNamespace{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vclusternamespaces").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VClusterNamespaces that match those selectors.
func (c *vClusterNamespaces) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VClusterNamespaceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VClusterNamespaceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vclusternamespaces").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vClusterNamespaces.
func (c *vClusterNamespaces) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vclusternamespaces").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vClusterNamespace and creates it.  Returns the server's representation of the vClusterNamespace, and an error, if there is any.
func (c *vClusterNamespaces) Create(ctx context.Context, vClusterNamespace *v1alpha1.VClusterNamespace, opts v1.CreateOptions) (result *v1alpha1.VClusterNamespace, err error) {
	result = &v1alpha1.VClusterNamespace{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vclusternamespaces").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vClusterNamespace).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vClusterNamespace and updates it. Returns the server's representation of the vClusterNamespace, and an error, if there is any.
func (c *vClusterNamespaces) Update(ctx context.Context, vClusterNamespace *v1alpha1.VClusterNamespace, opts v1.UpdateOptions) (result *v1alpha1.VClusterNamespace, err error) {
	result = &v1alpha1.VClusterNamespace{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vclusternamespaces").
		Name(vClusterNamespace.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vClusterNamespace).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vClusterNamespace and deletes it. Returns an error if one occurs.
func (c *vClusterNamespaces) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vclusternamespaces").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vClusterNamespaces) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vclusternamespaces").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vClusterNamespace.
func (c *vClusterNamespaces) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VClusterNamespace, err error) {
	result = &v1alpha1.VClusterNamespace{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vclusternamespaces").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
