{{- if .Values.fluentbit.kubeedge.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: prometheus-remote-write-edge
  labels:
    fluentbit.fluent.io/enabled: "true"
    node-role.kubernetes.io/edge: "true"
spec:
  matchRegex: (?:kubeedge|service)\.(.*)
  prometheusRemoteWrite:
    host: {{ .Values.fluentbit.kubeedge.prometheusRemoteWrite.host }}
    port: {{ .Values.fluentbit.kubeedge.prometheusRemoteWrite.port }}
    uri: /push
    addLabels : 
      app : fluentbit
      node: ${NODE_NAME}
      job : kubeedge
{{- end }}