---
kind: ConfigMap
apiVersion: v1
metadata:
  name: frpc
  namespace: {{ .Release.Namespace | quote }}
data:
  frpc.ini: |-
    [common]
    server_addr = {{ .Values.frpClientConfig.serverAddress }}
    server_port = {{ .Values.frpClientConfig.serverPort | default 7500 }}
    log_level=info
    token = {{ .Values.frpClientConfig.authToken | default "qingcloud" }}
    [{{ .Values.frpClientConfig.proxyName }}]
    type = stcp
    sk = {{ .Values.frpClientConfig.secretKey | default "abc001" }}
    local_ip=kubernetes
    local_port=443


---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frpc-proxy
  namespace: hami
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frpc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: frpc
      annotations:
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: frpc-config
          configMap:
            name: frpc
            defaultMode: 420
      containers:
        - name: kube-scheduler
          image: {{ .Values.defaultImageRegistry }}{{ .Values.scheduler.frpClientImage }}
          command:
            - /usr/bin/frpc
            - '-c'
            - /config/frpc.ini
          resources: {}
          volumeMounts:
            - name: frpc-config
              mountPath: /config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600