version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/cmd/edgewize-apiserver"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/cmd/controller-manager"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

