apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: router-manager
  name: {{.Values.serviceAccount.name}}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: router-manager
  name: router-manager-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: router-manager-manager-role
rules:
  - apiGroups:
      - rules.edgewize.io
    resources:
      - ruleendpoints
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rules.edgewize.io
    resources:
      - ruleendpoints/finalizers
    verbs:
      - update
  - apiGroups:
      - rules.edgewize.io
    resources:
      - ruleendpoints/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - rules.edgewize.io
    resources:
      - rules
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rules.edgewize.io
    resources:
      - rules/finalizers
    verbs:
      - update
  - apiGroups:
      - rules.edgewize.io
    resources:
      - rules/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: router-manager-metrics-auth-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: router-manager-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: router-manager
  name: router-manager-rule-editor-role
rules:
  - apiGroups:
      - rules.edgewize.io
    resources:
      - rules
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rules.edgewize.io
    resources:
      - rules/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: router-manager
  name: router-manager-rule-viewer-role
rules:
  - apiGroups:
      - rules.edgewize.io
    resources:
      - rules
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rules.edgewize.io
    resources:
      - rules/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: router-manager
  name: router-manager-ruleendpoint-editor-role
rules:
  - apiGroups:
      - rules.edgewize.io
    resources:
      - ruleendpoints
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rules.edgewize.io
    resources:
      - ruleendpoints/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: router-manager
  name: router-manager-ruleendpoint-viewer-role
rules:
  - apiGroups:
      - rules.edgewize.io
    resources:
      - ruleendpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rules.edgewize.io
    resources:
      - ruleendpoints/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: router-manager
  name: router-manager-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: router-manager-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{.Values.serviceAccount.name}}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: router-manager
  name: router-manager-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: router-manager-manager-role
subjects:
  - kind: ServiceAccount
    name: {{.Values.serviceAccount.name}}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: router-manager-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: router-manager-metrics-auth-role
subjects:
  - kind: ServiceAccount
    name: {{.Values.serviceAccount.name}}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.serviceAccount.name}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{.Values.serviceAccount.name}}
    namespace: {{ .Release.Namespace }}