kind: Service
apiVersion: v1
metadata:
  name: router-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "router-controller.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9090
  selector:
    {{- include "router-apiserver.selectorLabels" . | nindent 4 }}
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
---
kind: Service
apiVersion: v1
metadata:
  name: router-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "router-controller.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 8443
  selector:
    {{- include "router-controller.selectorLabels" . | nindent 4 }}
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "router-manager.fullname" . }}
  labels:
    {{- include "router-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.routerManager.service.type }}
  ports:
    - port: {{ .Values.routerManager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "router-manager.selectorLabels" . | nindent 4 }}
