apiVersion: v1
kind: ConfigMap
metadata:
  name: whizard-edge-metrics-configmap
  namespace: kubesphere-monitoring-system
data:
  metrics_to_keep.yaml: |-
    global:
      - action: "keep"
        regex: "node_(uname|network)_info|node_cpu_.+|node_memory_Mem.+_bytes|node_memory_SReclaimable_bytes|node_memory_Cached_bytes|node_memory_Buffers_bytes|node_network_(.+_bytes_total|up)|node_network_.+_errs_total|node_nf_conntrack_entries.*|node_disk_.+_completed_total|node_disk_.+_bytes_total|node_filesystem_files|node_filesystem_files_free|node_filesystem_avail_bytes|node_filesystem_size_bytes|node_filesystem_free_bytes|node_filesystem_readonly|node_load.+|node_timex_offset_seconds"

      - action: "keep"
        regex: "container_cpu_usage_seconds_total|container_memory_usage_bytes|container_memory_cache|container_network_.+_bytes_total|container_memory_working_set_bytes|container_cpu_cfs_.*periods_total|container_processes.*|container_threads.*"

      - action: "keep"
        regex: "DCGM_FI_PROF_GR_ENGINE_ACTIVE|DCGM_FI_DEV_.+"

      - action: "keep"
        regex: "machine_npu_nums|machine_npu_name|npu_chip_info_.+|container_npu_.+"