apiVersion: v1
kind: ConfigMap
metadata:
  name: whizard-edge-agent-proxy-configmap
  namespace: kubesphere-monitoring-system
data:
  config.yml: |
    # Where to listen for incoming write requests from Prometheus
    listen: 0.0.0.0:8080
    # Profiling API, remove to disable
    listen_pprof: 0.0.0.0:7008
    # Where to send the modified requests (Prometheus)
    target: http://prometheus-operated.kubesphere-monitoring-system:9090/api/v1/write
    # Log level
    log_level: warn
    # HTTP request timeout
    timeout: 10s
    # Timeout to wait on shutdown to allow load balancers detect that we're going away.
    # During this period after the shutdown command the /alive endpoint will reply with HTTP 503.
    # Set to 0s to disable.
    timeout_shutdown: 10s
    # Max number of parallel incoming HTTP requests to handle
    concurrency: 1000

    

