apiVersion: v1
kind: Service
metadata:
  name: whizard-edge-agent-proxy
  namespace: kubesphere-monitoring-system
spec:
  {{- if .Values.edge_agent.nodePort }}
  type: NodePort
  {{- else}}
  type: ClusterIP
  {{- end}}
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    {{- if .Values.edge_agent.nodePort }}
      nodePort: {{ .Values.edge_agent.nodePort }}
    {{- end }}
  selector:
    app: whizard-edge-agent-proxy
