blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/edgewize-io/edgewize/discussions
    about: I have questions about EdgeWize. Please ask and answer questions at https://github.com/edgewize-io/edgewize/discussions
