/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/edgewize-io/edgewize/pkg/apis/apps/v1alpha1"
	scheme "github.com/edgewize-io/edgewize/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// InferModelDeploymentsGetter has a method to return a InferModelDeploymentInterface.
// A group's client should implement this interface.
type InferModelDeploymentsGetter interface {
	InferModelDeployments(namespace string) InferModelDeploymentInterface
}

// InferModelDeploymentInterface has methods to work with InferModelDeployment resources.
type InferModelDeploymentInterface interface {
	Create(ctx context.Context, inferModelDeployment *v1alpha1.InferModelDeployment, opts v1.CreateOptions) (*v1alpha1.InferModelDeployment, error)
	Update(ctx context.Context, inferModelDeployment *v1alpha1.InferModelDeployment, opts v1.UpdateOptions) (*v1alpha1.InferModelDeployment, error)
	UpdateStatus(ctx context.Context, inferModelDeployment *v1alpha1.InferModelDeployment, opts v1.UpdateOptions) (*v1alpha1.InferModelDeployment, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.InferModelDeployment, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.InferModelDeploymentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InferModelDeployment, err error)
	InferModelDeploymentExpansion
}

// inferModelDeployments implements InferModelDeploymentInterface
type inferModelDeployments struct {
	client rest.Interface
	ns     string
}

// newInferModelDeployments returns a InferModelDeployments
func newInferModelDeployments(c *AppsV1alpha1Client, namespace string) *inferModelDeployments {
	return &inferModelDeployments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the inferModelDeployment, and returns the corresponding inferModelDeployment object, and an error if there is any.
func (c *inferModelDeployments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.InferModelDeployment, err error) {
	result = &v1alpha1.InferModelDeployment{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("infermodeldeployments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of InferModelDeployments that match those selectors.
func (c *inferModelDeployments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InferModelDeploymentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.InferModelDeploymentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("infermodeldeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested inferModelDeployments.
func (c *inferModelDeployments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("infermodeldeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a inferModelDeployment and creates it.  Returns the server's representation of the inferModelDeployment, and an error, if there is any.
func (c *inferModelDeployments) Create(ctx context.Context, inferModelDeployment *v1alpha1.InferModelDeployment, opts v1.CreateOptions) (result *v1alpha1.InferModelDeployment, err error) {
	result = &v1alpha1.InferModelDeployment{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("infermodeldeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(inferModelDeployment).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a inferModelDeployment and updates it. Returns the server's representation of the inferModelDeployment, and an error, if there is any.
func (c *inferModelDeployments) Update(ctx context.Context, inferModelDeployment *v1alpha1.InferModelDeployment, opts v1.UpdateOptions) (result *v1alpha1.InferModelDeployment, err error) {
	result = &v1alpha1.InferModelDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("infermodeldeployments").
		Name(inferModelDeployment.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(inferModelDeployment).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *inferModelDeployments) UpdateStatus(ctx context.Context, inferModelDeployment *v1alpha1.InferModelDeployment, opts v1.UpdateOptions) (result *v1alpha1.InferModelDeployment, err error) {
	result = &v1alpha1.InferModelDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("infermodeldeployments").
		Name(inferModelDeployment.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(inferModelDeployment).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the inferModelDeployment and deletes it. Returns an error if one occurs.
func (c *inferModelDeployments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("infermodeldeployments").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *inferModelDeployments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("infermodeldeployments").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched inferModelDeployment.
func (c *inferModelDeployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InferModelDeployment, err error) {
	result = &v1alpha1.InferModelDeployment{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("infermodeldeployments").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
