apiVersion: v1
kind: ConfigMap
metadata:
  name: model-mesh-broker
  namespace: {{ .Release.Namespace }}
data:
  model-mesh-broker.yaml: |
    {{- .Values.modelMeshBroker.conf | toYaml | nindent 4 }}
