apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "model-service-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "model-service-controller.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "model-service-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "model-service-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "model-mesh-msc.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "model-service-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "model-mesh-msc"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ template "model-mesh-msc.image" . }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /readyz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: msc-config
              mountPath: /etc/model-service-controller
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: msc-config
          configMap:
            name: model-mesh-msc
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
