apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: npu-exporter
  namespace: kubesphere-monitoring-system
spec:
  selector:
    matchLabels:
      app: npu-exporter
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        app: npu-exporter
    spec:
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{ end }}
      hostNetwork: true
      tolerations:
        - key: node-role.kubernetes.io/edge
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: accelerator
                    operator: In
                    values:
                      - huawei-Ascend310
                  {{- include "whizard-edge-agent.edgeNodeAffinity" . | nindent 18 }}
      containers:
      - name: npu-exporter
        image: "{{ .Values.defaultImageRegistry }}{{ .Values.npu_exporter.image.repository }}:{{ .Values.npu_exporter.image.tag }}"
        resources:
          requests:
              memory: 1000Mi
              cpu: 1000m
          limits:
              memory: 1000Mi
              cpu: 1000m
        imagePullPolicy: "{{ .Values.npu_exporter.image.pullPolicy }}"
        command: [ "/bin/bash", "-c", "--"]
        # pair firstly
        args: [ "umask 027;npu-exporter -port=8082 -ip=0.0.0.0  -updateTime=5 -enableHTTP=true
                 -logFile=/var/log/mindx-dl/npu-exporter/npu-exporter.log -logLevel=0 -containerMode=docker" ]
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
          runAsUser: 0
          runAsGroup: 0
        ports:
          - name: http
            containerPort: 8082
            protocol: TCP
        volumeMounts:
          - name: log-npu-exporter
            mountPath: /var/log/mindx-dl/npu-exporter
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: ascend-driver
            mountPath: /usr/local/Ascend/driver
            readOnly: true
          - name: ascend-dcmi
            mountPath: /usr/local/dcmi
            readOnly: true
          - name: sys
            mountPath: /sys
            readOnly: true
          - name: docker-shim  # delete when only use containerd
            mountPath: /var/run/dockershim.sock
            readOnly: true
          - name: docker  # delete when only use containerd
            mountPath: /var/run/docker
            readOnly: true
          - name: containerd
            mountPath: /run/containerd
            readOnly: true
          - name: tmp
            mountPath: /tmp
      volumes:
        - name: log-npu-exporter
          hostPath:
            path: /var/log/mindx-dl/npu-exporter
            type: Directory
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: ascend-driver
          hostPath:
            path: /usr/local/Ascend/driver
        - name: ascend-dcmi
          hostPath:
            path: /usr/local/dcmi
        - name: sys
          hostPath:
            path: /sys
        - name: docker-shim # delete when only use containerd
          hostPath:
            path: /var/run/dockershim.sock
        - name: docker  # delete when only use containerd
          hostPath:
            path: /var/run/docker
        - name: containerd
          hostPath:
            path: /run/containerd
        - name: tmp
          hostPath:
            path: /tmp
