{{- if ne .Values.role "host" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: whizard-agent-proxy
    app.kubernetes.io/name: whizard-agent-proxy
  name: whizard-agent-proxy
  namespace: kubesphere-monitoring-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: whizard-agent-proxy
      app.kubernetes.io/name: whizard-agent-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: whizard-agent-proxy
        app.kubernetes.io/name: whizard-agent-proxy
    spec:
      containers:
        - args:
            - --gateway.address=http://gateway-whizard-operated.kubesphere-monitoring-system.svc:9090 # 根据 host 集群中 whizard gateway 暴露的地址和端口修改，为了向部署在 Host 集群的 Whizard 通过 remote-write 写入监控数据以及查询监控、告警等数据
            - --tenant={{ .Values.whizard_agent_proxy.tenant }}
          image: {{ template "edgewize-whizard-adapter.image" . }}
          name: agent-proxy
          ports:
            - containerPort: 9090
              name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: whizard-agent-proxy
    app.kubernetes.io/name: whizard-agent-proxy
  name: whizard-agent-proxy
  namespace: kubesphere-monitoring-system
spec:
  ports:
    - name: http
      port: 9090
      targetPort: http
  selector:
    app.kubernetes.io/instance: whizard-agent-proxy
    app.kubernetes.io/name: whizard-agent-proxy
  sessionAffinity: ClientIP
{{- end }}