apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: whizard-agent-proxy
    app.kubernetes.io/name: whizard-agent-proxy
  name: whizard-agent-proxy
  namespace: kubesphere-monitoring-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: whizard-agent-proxy
      app.kubernetes.io/name: whizard-agent-proxy
  template:
    metadata:
      labels:
        IndexByEdgeWize: "true"
        app.kubernetes.io/instance: whizard-agent-proxy
        app.kubernetes.io/name: whizard-agent-proxy
    spec:
      containers:
        - args:
            - --gateway.address={{ .Values.whizard_agent_proxy.gateway_address | default "http://gateway-whizard-operated.kubesphere-monitoring-system.svc:9090" }}
            - --tenant={{ .Values.whizard_agent_proxy.tenant }}
          image: {{ .Values.defaultImageRegistry }}{{ .Values.whizard_agent_proxy.image.repository }}:{{ .Values.whizard_agent_proxy.image.tag }}
          name: agent-proxy
          ports:
            - containerPort: 9090
              name: http
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{ end }}
      {{- if eq .Values.clusterType "auto" }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/edge
                    operator: DoesNotExist
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: whizard-agent-proxy
    app.kubernetes.io/name: whizard-agent-proxy
  name: whizard-agent-proxy
  namespace: kubesphere-monitoring-system
spec:
  ports:
    - name: http
      port: 9090
      targetPort: http
  selector:
    app.kubernetes.io/instance: whizard-agent-proxy
    app.kubernetes.io/name: whizard-agent-proxy
  sessionAffinity: ClientIP
