/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/edgewize-io/edgewize/pkg/apis/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInferModelTemplates implements InferModelTemplateInterface
type FakeInferModelTemplates struct {
	Fake *FakeAppsV1alpha1
}

var infermodeltemplatesResource = schema.GroupVersionResource{Group: "apps.edgewize.io", Version: "v1alpha1", Resource: "infermodeltemplates"}

var infermodeltemplatesKind = schema.GroupVersionKind{Group: "apps.edgewize.io", Version: "v1alpha1", Kind: "InferModelTemplate"}

// Get takes name of the inferModelTemplate, and returns the corresponding inferModelTemplate object, and an error if there is any.
func (c *FakeInferModelTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.InferModelTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(infermodeltemplatesResource, name), &v1alpha1.InferModelTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelTemplate), err
}

// List takes label and field selectors, and returns the list of InferModelTemplates that match those selectors.
func (c *FakeInferModelTemplates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InferModelTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(infermodeltemplatesResource, infermodeltemplatesKind, opts), &v1alpha1.InferModelTemplateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.InferModelTemplateList{ListMeta: obj.(*v1alpha1.InferModelTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.InferModelTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested inferModelTemplates.
func (c *FakeInferModelTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(infermodeltemplatesResource, opts))
}

// Create takes the representation of a inferModelTemplate and creates it.  Returns the server's representation of the inferModelTemplate, and an error, if there is any.
func (c *FakeInferModelTemplates) Create(ctx context.Context, inferModelTemplate *v1alpha1.InferModelTemplate, opts v1.CreateOptions) (result *v1alpha1.InferModelTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(infermodeltemplatesResource, inferModelTemplate), &v1alpha1.InferModelTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelTemplate), err
}

// Update takes the representation of a inferModelTemplate and updates it. Returns the server's representation of the inferModelTemplate, and an error, if there is any.
func (c *FakeInferModelTemplates) Update(ctx context.Context, inferModelTemplate *v1alpha1.InferModelTemplate, opts v1.UpdateOptions) (result *v1alpha1.InferModelTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(infermodeltemplatesResource, inferModelTemplate), &v1alpha1.InferModelTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelTemplate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInferModelTemplates) UpdateStatus(ctx context.Context, inferModelTemplate *v1alpha1.InferModelTemplate, opts v1.UpdateOptions) (*v1alpha1.InferModelTemplate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(infermodeltemplatesResource, "status", inferModelTemplate), &v1alpha1.InferModelTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelTemplate), err
}

// Delete takes name of the inferModelTemplate and deletes it. Returns an error if one occurs.
func (c *FakeInferModelTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(infermodeltemplatesResource, name, opts), &v1alpha1.InferModelTemplate{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInferModelTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(infermodeltemplatesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.InferModelTemplateList{})
	return err
}

// Patch applies the patch and returns the patched inferModelTemplate.
func (c *FakeInferModelTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InferModelTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(infermodeltemplatesResource, name, pt, data, subresources...), &v1alpha1.InferModelTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelTemplate), err
}
