/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/edgewize-io/edgewize/pkg/apis/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInferModelTemplateVersions implements InferModelTemplateVersionInterface
type FakeInferModelTemplateVersions struct {
	Fake *FakeAppsV1alpha1
}

var infermodeltemplateversionsResource = schema.GroupVersionResource{Group: "apps.edgewize.io", Version: "v1alpha1", Resource: "infermodeltemplateversions"}

var infermodeltemplateversionsKind = schema.GroupVersionKind{Group: "apps.edgewize.io", Version: "v1alpha1", Kind: "InferModelTemplateVersion"}

// Get takes name of the inferModelTemplateVersion, and returns the corresponding inferModelTemplateVersion object, and an error if there is any.
func (c *FakeInferModelTemplateVersions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.InferModelTemplateVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(infermodeltemplateversionsResource, name), &v1alpha1.InferModelTemplateVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelTemplateVersion), err
}

// List takes label and field selectors, and returns the list of InferModelTemplateVersions that match those selectors.
func (c *FakeInferModelTemplateVersions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InferModelTemplateVersionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(infermodeltemplateversionsResource, infermodeltemplateversionsKind, opts), &v1alpha1.InferModelTemplateVersionList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.InferModelTemplateVersionList{ListMeta: obj.(*v1alpha1.InferModelTemplateVersionList).ListMeta}
	for _, item := range obj.(*v1alpha1.InferModelTemplateVersionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested inferModelTemplateVersions.
func (c *FakeInferModelTemplateVersions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(infermodeltemplateversionsResource, opts))
}

// Create takes the representation of a inferModelTemplateVersion and creates it.  Returns the server's representation of the inferModelTemplateVersion, and an error, if there is any.
func (c *FakeInferModelTemplateVersions) Create(ctx context.Context, inferModelTemplateVersion *v1alpha1.InferModelTemplateVersion, opts v1.CreateOptions) (result *v1alpha1.InferModelTemplateVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(infermodeltemplateversionsResource, inferModelTemplateVersion), &v1alpha1.InferModelTemplateVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelTemplateVersion), err
}

// Update takes the representation of a inferModelTemplateVersion and updates it. Returns the server's representation of the inferModelTemplateVersion, and an error, if there is any.
func (c *FakeInferModelTemplateVersions) Update(ctx context.Context, inferModelTemplateVersion *v1alpha1.InferModelTemplateVersion, opts v1.UpdateOptions) (result *v1alpha1.InferModelTemplateVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(infermodeltemplateversionsResource, inferModelTemplateVersion), &v1alpha1.InferModelTemplateVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelTemplateVersion), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInferModelTemplateVersions) UpdateStatus(ctx context.Context, inferModelTemplateVersion *v1alpha1.InferModelTemplateVersion, opts v1.UpdateOptions) (*v1alpha1.InferModelTemplateVersion, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(infermodeltemplateversionsResource, "status", inferModelTemplateVersion), &v1alpha1.InferModelTemplateVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelTemplateVersion), err
}

// Delete takes name of the inferModelTemplateVersion and deletes it. Returns an error if one occurs.
func (c *FakeInferModelTemplateVersions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(infermodeltemplateversionsResource, name, opts), &v1alpha1.InferModelTemplateVersion{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInferModelTemplateVersions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(infermodeltemplateversionsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.InferModelTemplateVersionList{})
	return err
}

// Patch applies the patch and returns the patched inferModelTemplateVersion.
func (c *FakeInferModelTemplateVersions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InferModelTemplateVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(infermodeltemplateversionsResource, name, pt, data, subresources...), &v1alpha1.InferModelTemplateVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InferModelTemplateVersion), err
}
