apiVersion: v1
kind: ConfigMap
metadata:
  name: edgewize-config
data:
  edgewize.yaml: |
    authentication:
      mode: AllowAlways
      authenticateRateLimiterMaxTries: {{ .Values.config.authentication.authenticateRateLimiterMaxTries | default 10 }}
      authenticateRateLimiterDuration: {{ .Values.config.authentication.authenticationRateLimiterDuration | default "10m0s" }}
      loginHistoryRetentionPeriod: {{ .Values.config.authentication.loginHistoryRetentionPeriod | default "168h"  }}
      maximumClockSkew: {{ .Values.config.authentication.maximumClockSkew | default "10s" }}
      jwtSecret: "{{ .Values.config.jwtSecret | default (randAlphaNum 32 ) }}"
{{- if .Values.config.authentication.oauthOptions }}
      {{- with .Values.config.authentication.oauthOptions }}
      oauthOptions:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- else if eq (default .Values.config.multicluster.clusterRole "none") "member" }}
      oauthOptions:
        accessTokenMaxAge: 0
{{- end }}
    monitoring:
      endpoint: {{ .Values.config.monitoring.endpoint | default "http://whizard-agent-proxy.kubesphere-monitoring-system.svc:9090" }}
    alerting:
      endpoint: {{ .Values.config.alerting.endpoint | default "" }}
      prometheusEndpoint: {{ .Values.config.alerting.prometheusEndpoint | default "" }}
      thanosRulerEndpoint: {{ .Values.config.alerting.thanosRulerEndpoint | default "http://query-frontend-whizard-operated.kubesphere-monitoring-system.svc:10902" }}
      thanosRuleResourceLabels:  {{ .Values.config.alerting.thanosRuleResourceLabels | default "" }}
    notification:
      endpoint: {{ .Values.config.notification.endpoint | default "http://notification-manager-svc.edgewize-monitoring-system.svc:19093" }}
    {{- with .Values.config.servicemesh }}
    servicemesh:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    edgewize:
      gateway:
        {{- if (eq (len .Values.gateway.advertiseAddress) 0) }}
        advertiseAddress: []
        {{- else }}
        advertiseAddress:
          {{- toYaml .Values.gateway.advertiseAddress | nindent 8 }}
        {{- end }}
        {{- if (eq (len .Values.gateway.dnsNames) 0) }}
        dnsNames: []
        {{- else }}
        dnsNames:
          {{- toYaml .Values.gateway.dnsNames | nindent 8 }}
        {{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: edgewize-gateway-middlewares
  namespace: edgewize-system
  annotations:
    kubesphere.io/creator: admin
data:
  middleware.yaml: |-
    cloudhub:
      websocket_rate_limit:
        upbyterate: 200
        upburstlimit: 409600
        downbyterate: 200
        downburstlimit: 409600
        timewindow: 1
    tunnelport:
      websocket_rate_limit:
        upbyterate: 200
        upburstlimit: 409600
        downbyterate: 200
        downburstlimit: 409600
        timewindow: 1
