{{- $existing := (lookup "v1" "ConfigMap" "edgewize-system" "edgecluster-service") -}}
{{- if not $existing }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgecluster-service
data:
  edgewize-servers.yaml: ""
{{- else }}
{{- toYaml $existing | nindent 0 }}
{{- end }}