{{- $rootCA := buildCustomCert .Values.certificateAuthority.crt .Values.certificateAuthority.key -}}
{{- $ips := .Values.gateway.advertiseAddress }}
{{- $domains := .Values.gateway.dnsNames }}
{{- $cn := printf "EdgeWize" }}
{{- $cert := genSignedCert $cn $ips $domains 36500 $rootCA -}}
{{- $edgecn := printf "EdgeGateway" }}
{{- $whizardEdgeGatewayIPs := .Values.whizardEdgeGateway.advertiseAddress }}
{{- $whizardEdgeGatewayDomains := .Values.whizardEdgeGateway.dnsNames }}
{{- $whizardEdgeGatewayCert := genSignedCert $edgecn $whizardEdgeGatewayIPs $whizardEdgeGatewayDomains 36500 $rootCA -}}

apiVersion: v1
kind: Secret
metadata:
  name: edgewize-gateway-certs
data:
  server.ca: {{ $rootCA.Cert | b64enc }}
  server.crt: {{ $cert.Cert | b64enc }}
  server.key: {{ $cert.Key | b64enc }}
  client.crt: {{ $cert.Cert | b64enc }}
  client.key: {{ $cert.Key | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: edgewize-root-ca
data:
  cacrt: {{ $rootCA.Cert | b64enc }}
  cakey: {{ $rootCA.Key | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: whizard-edge-gateway-certs
  namespace: kubesphere-monitoring-system
data:
  server.ca: {{ $rootCA.Cert | b64enc }}
  server.crt: {{ $whizardEdgeGatewayCert.Cert | b64enc }}
  server.key: {{ $whizardEdgeGatewayCert.Key | b64enc }}
