apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: whizard-edge-gateway
    app.kubernetes.io/name: whizard-edge-gateway
  name: whizard-edge-gateway
  namespace: kubesphere-monitoring-system
spec:
  replicas: {{ .Values.whizardEdgeGateway.replicas }}
  selector:
    matchLabels:
      app: whizard-edge-gateway
  template:
    metadata:
      labels:
        app: whizard-edge-gateway
    spec:
      {{- include "whizardEdgeGateway.imagePullSecrets" . | nindent 6 }}
      containers:
        - image: {{ template "whizard-edge-gateway.image" . }}
          imagePullPolicy: {{ .Values.whizardEdgeGateway.image.pullPolicy }}
          name: whizard-edge-gateway
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/whizard-edge-gateway
              name: whizard-edge-gateway-config
            - mountPath: /etc/ssl/whizard
              name: edge-certificates-secret
          resources:
            limits:
              cpu: '3'
              memory: 6Gi
            requests:
              cpu: 600m
              memory: 800Mi
      volumes:
        - configMap:
            name: whizard-edge-gateway-configmap
          name: whizard-edge-gateway-config
        - secret:
            secretName: whizard-edge-gateway-certs
            defaultMode: 420
          name: edge-certificates-secret

---

{{- $existing := (lookup "v1" "ConfigMap" "kubesphere-monitoring-system" "whizard-edge-gateway-configmap") -}}
{{- if not $existing }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: whizard-edge-gateway-configmap
  namespace: kubesphere-monitoring-system
data:
  config.yaml: ""
{{- else }}
{{- toYaml $existing | nindent 0 }}
{{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: whizard-edge-gateway
  namespace: kubesphere-monitoring-system
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
      {{- if .Values.whizardEdgeGateway.nodePort }}
      nodePort: {{ .Values.whizardEdgeGateway.nodePort }}
      {{ end }}
  {{- if .Values.whizardEdgeGateway.nodePort }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  selector:
    app: whizard-edge-gateway
