apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: whizard-edge-gateway
    app.kubernetes.io/name: whizard-edge-gateway
  name: whizard-edge-gateway
  namespace: kubesphere-monitoring-system
spec:
  replicas: {{ .Values.whizardEdgeGateway.replicas }}
  selector:
    matchLabels:
      app: whizard-edge-gateway
  template:
    metadata:
      labels:
        app: whizard-edge-gateway
    spec:
      {{- include "whizardEdgeGateway.imagePullSecrets" . | nindent 6 }}
      containers:
        - image: {{ template "whizard-edge-gateway.image" . }}
          imagePullPolicy: {{ .Values.whizardEdgeGateway.image.pullPolicy }}
          name: whizard-edge-gateway
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/whizard-edge-gateway
              name: whizard-edge-gateway-config
            - mountPath: /etc/whizard-edge-metrics
              name: whizard-edge-metrics-config
            - mountPath: /etc/ssl/whizard
              name: edge-certificates-secret
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 500Mi
      volumes:
        - configMap:
            name: whizard-edge-gateway-configmap
          name: whizard-edge-gateway-config
        - configMap:
            name: whizard-edge-metrics-configmap
          name: whizard-edge-metrics-config
        - secret:
            secretName: whizard-edge-gateway-certs
            defaultMode: 420
          name: edge-certificates-secret

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: whizard-edge-gateway-configmap
  namespace: kubesphere-monitoring-system
data:
  config.yaml: |
    # Where to listen for incoming write requests from Prometheus
    listen: 0.0.0.0:8080
    # Profiling API, remove to disable
    listen_pprof: 0.0.0.0:7008

    # Log level
    log_level: info
    # HTTP request timeout
    timeout: 10s
    # Timeout to wait on shutdown to allow load balancers detect that we're going away.
    # During this period after the shutdown command the /alive endpoint will reply with HTTP 503.
    # Set to 0s to disable.
    timeout_shutdown: 10s
    # Max number of parallel incoming HTTP requests to handle
    concurrency: 4000
    {{- if .Values.whizardEdgeGateway.tlsEnable }}
    # path of edge certificates
    cert_dir: "/etc/ssl/whizard"
    {{- end }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: whizard-edge-metrics-configmap
  namespace: kubesphere-monitoring-system
data:
  metrics_to_keep.yaml: |-
    global:
      - action: "keep"
        regex: "node_(uname|network)_info|node_cpu_.+|node_memory_Mem.+_bytes|node_memory_SReclaimable_bytes|node_memory_Cached_bytes|node_memory_Buffers_bytes|node_network_(.+_bytes_total|up)|node_network_.+_errs_total|node_nf_conntrack_entries.*|node_disk_.+_completed_total|node_disk_.+_bytes_total|node_filesystem_files|node_filesystem_files_free|node_filesystem_avail_bytes|node_filesystem_size_bytes|node_filesystem_free_bytes|node_filesystem_readonly|node_load.+|node_timex_offset_seconds"

      - action: "keep"
        regex: "container_cpu_usage_seconds_total|container_memory_usage_bytes|container_memory_cache|container_network_.+_bytes_total|container_memory_working_set_bytes|container_cpu_cfs_.*periods_total|container_processes.*|container_threads.*"

      - action: "keep"
        regex: "DCGM_FI_PROF_GR_ENGINE_ACTIVE|DCGM_FI_DEV_.+"

      - action: "keep"
        regex: "machine_npu_nums|machine_npu_name|npu_chip_info_.+|container_npu_.+"

---

apiVersion: v1
kind: Service
metadata:
  name: whizard-edge-gateway
  namespace: kubesphere-monitoring-system
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
      {{- if .Values.whizardEdgeGateway.nodePort }}
      nodePort: {{ .Values.whizardEdgeGateway.nodePort }}
      {{ end }}
  {{- if .Values.whizardEdgeGateway.nodePort }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  selector:
    app: whizard-edge-gateway
