{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubesphere-config
data:
  kubesphere.yaml: |
    authentication:
      authenticateRateLimiterMaxTries: {{ .Values.config.authentication.authenticateRateLimiterMaxTries | default 10 }}
      authenticateRateLimiterDuration: {{ .Values.config.authentication.authenticationRateLimiterDuration | default "10m0s" }}
      loginHistoryRetentionPeriod: {{ .Values.config.authentication.loginHistoryRetentionPeriod | default "168h"  }}
      maximumClockSkew: {{ .Values.config.authentication.maximumClockSkew | default "10s" }}
      multipleLogin: {{ .Values.console.enableMultiLogin | default true }}
      kubectlImage: {{ .Values.defaultImageRegistry }}{{ .Values.image.ks_kubectl_repo }}:{{ .Values.image.ks_kubectl_tag | default "latest" }}
      jwtSecret: "{{ .Values.config.jwtSecret | default (randAlphaNum 32 ) }}"
{{- if .Values.config.authentication.oauthOptions }}
      {{- with .Values.config.authentication.oauthOptions }}
      oauthOptions:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- else if eq (default .Values.config.multicluster.clusterRole "none") "member" }}
      oauthOptions:
        accessTokenMaxAge: 0
{{- end }}
    multicluster:
      enable: true
      clusterRole: member
    monitoring:
      endpoint: {{ .Values.config.monitoring.endpoint | default "http://whizard-agent-proxy.kubesphere-monitoring-system.svc:9090" }}
    alerting:
      endpoint: {{ .Values.config.alerting.endpoint | default "" }}
      prometheusEndpoint: {{ .Values.config.alerting.prometheusEndpoint | default "" }}
      thanosRulerEndpoint: {{ .Values.config.alerting.thanosRulerEndpoint | default "http://whizard-agent-proxy.kubesphere-monitoring-system.svc:9090" }}
      thanosRuleResourceLabels:  {{ .Values.config.alerting.thanosRuleResourceLabels | default "" }}
    notification:
      endpoint: {{ .Values.config.notification.endpoint | default "http://notification-manager-svc.kubesphere-monitoring-system.svc:19093" }}
    edgewizeota:
      endpoint: {{ .Values.config.edgewizeota.endpoint | default "http://edge-ota-server.kubeedge.svc/api/" }}

    {{- with .Values.config.servicemesh }}
    servicemesh:
      {{- toYaml . | nindent 6 }}
    {{- end }}

{{- end }}
