{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubesphere-config
data:
  kubesphere.yaml: |
    authentication:
      authenticateRateLimiterMaxTries: {{ .Values.config.authentication.authenticateRateLimiterMaxTries | default 10 }}
      authenticateRateLimiterDuration: {{ .Values.config.authentication.authenticationRateLimiterDuration | default "10m0s" }}
      loginHistoryRetentionPeriod: {{ .Values.config.authentication.loginHistoryRetentionPeriod | default "168h"  }}
      maximumClockSkew: {{ .Values.config.authentication.maximumClockSkew | default "10s" }}
      multipleLogin: {{ .Values.console.enableMultiLogin | default true }}
      kubectlImage: {{ .Values.defaultImageRegistry }}{{ .Values.image.ks_kubectl_repo }}:{{ .Values.image.ks_kubectl_tag | default "latest" }}
      jwtSecret: "{{ .Values.config.jwtSecret | default (randAlphaNum 32 ) }}"
{{- if .Values.config.authentication.oauthOptions }}
      {{- with .Values.config.authentication.oauthOptions }}
      oauthOptions:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- else if eq (default .Values.config.multicluster.clusterRole "none") "member" }}
      oauthOptions:
        accessTokenMaxAge: 0
{{- end }}
    multicluster:
      clusterRole: member
    auditing:
      enable: {{ .Values.config.auditing.enable | default false }}
      webhookUrl: {{ .Values.config.auditing.webhookUrl }}
      eventSendersNum: {{ .Values.config.auditing.eventSendersNum | default 0 }}
      eventBatchSize: {{ .Values.config.auditing.eventBatchSize | default 0 }}
      eventBatchInterval: {{ .Values.config.auditing.eventBatchInterval | default "0s" }}
      host: {{ .Values.config.auditing.host }}
      basicAuth: {{ .Values.config.auditing.basicAuth | default true }}
      username: {{ .Values.config.auditing.username | default "admin" }}
      password: {{ .Values.config.auditing.password | default "admin" }}
      indexPrefix: {{ .Values.config.auditing.indexPrefix }}
      version: {{ .Values.config.auditing.version | default "" }}
      mode: {{ .Values.config.auditing.mode | default "" }}
    logging:
      host: {{ .Values.config.logging.host }}
      basicAuth: {{ .Values.config.logging.basicAuth | default true }}
      username: {{ .Values.config.logging.username }}
      password: {{ .Values.config.logging.password }}
      indexPrefix: {{ .Values.config.logging.indexPrefix }}
      version: ""
    monitoring:
      endpoint: {{ .Values.config.monitoring.endpoint | default "http://whizard-agent-proxy.kubesphere-monitoring-system.svc:9090" }}
    alerting:
      endpoint: {{ .Values.config.alerting.endpoint | default "" }}
      prometheusEndpoint: {{ .Values.config.alerting.prometheusEndpoint | default "" }}
      thanosRulerEndpoint: {{ .Values.config.alerting.thanosRulerEndpoint | default "http://whizard-agent-proxy.kubesphere-monitoring-system.svc:9090" }}
      thanosRuleResourceLabels:  {{ .Values.config.alerting.thanosRuleResourceLabels | default "" }}
    notification:
      endpoint: ""
    edgewizeota:
      endpoint: {{ .Values.config.edgewizeota.endpoint | default "http://edge-ota-server.edgewize-system.svc/api/" }}
    edgewizerule:
      endpoint: {{ .Values.config.edgewizerule.endpoint | default "http://router-apiserver.edgewize-system.svc:80/kapis/rules.edgewize.io/" }}
    edgewizemessage:
      endpoint: {{ .Values.config.edgewizemessage.endpoint | default "http://router-manager.edgewize-system.svc:8000" }}

    {{- with .Values.config.servicemesh }}
    servicemesh:
      {{- toYaml . | nindent 6 }}
    {{- end }}

{{- end }}
