apiVersion: iam.kubesphere.io/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.kubesphere.io/module: Access Control
    iam.kubesphere.io/role-template-rules: '{"nodegroups": "view"}'
    kubesphere.io/alias-name: NodeGroups View
  labels:
    iam.kubesphere.io/role-template: 'true'
    kubefed.io/managed: 'true'
  name: role-template-view-nodegroups
rules:
  - apiGroups:
      - 'infra.kubesphere.io'
    resources:
      - 'nodegroups'
      - 'nodes'
      - 'namespaces'
    verbs:
      - 'list'
      - 'get'
      - 'watch'
  - apiGroups:
      - 'iam.kubesphere.io'
    resources:
      - 'roles'
      - 'members'
      - 'members/nodegrouproles'
    verbs:
      - 'list'
      - 'get'
      - 'watch'

---
apiVersion: iam.kubesphere.io/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.kubesphere.io/dependencies: '["role-template-view-nodegroups"]'
    iam.kubesphere.io/module: Access Control
    iam.kubesphere.io/role-template-rules: '{"nodegroups": "manage"}'
    kubesphere.io/alias-name: NodeGroups Management
  labels:
    iam.kubesphere.io/role-template: 'true'
    kubefed.io/managed: 'true'
  name: role-template-manage-nodegroups
rules:
  - apiGroups:
      - 'infra.kubesphere.io'
    resources:
      - 'nodegroups'
      - 'nodes'
      - 'namespaces'
    verbs:
      - '*'
  - apiGroups:
      - 'iam.kubesphere.io'
    resources:
      - 'roles'
      - 'members'
      - 'members/nodegrouproles'
    verbs:
      - '*'

---
apiVersion: iam.kubesphere.io/v1alpha2
kind: NodeGroupRole
metadata:
  annotations:
    iam.kubesphere.io/module: Access Control
    iam.kubesphere.io/role-template-rules: '{"nodegroups": "view"}'
    kubesphere.io/alias-name: NodeGroups View
  labels:
    iam.kubesphere.io/role-template: 'true'
  name: role-template-view-nodegroups
rules:
  - apiGroups:
      - 'infra.kubesphere.io'
    resources:
      - 'nodegroups'
      - 'nodes'
      - 'namespaces'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'resources.kubesphere.io'
    resources:
      - 'namespaces'
      - 'services'
    verbs:
      - 'get'
      - 'list'
      - 'watch'

---
apiVersion: iam.kubesphere.io/v1alpha2
kind: NodeGroupRole
metadata:
  annotations:
    iam.kubesphere.io/dependencies: '["role-template-view-nodegroups"]'
    iam.kubesphere.io/module: Access Control
    iam.kubesphere.io/role-template-rules: '{"nodegroups": "manage"}'
    kubesphere.io/alias-name: NodeGroups Management
  labels:
    iam.kubesphere.io/role-template: 'true'
  name: role-template-manage-nodegroups
rules:
  - apiGroups:
      - 'infra.kubesphere.io'
    resources:
      - 'nodegroups'
      - 'nodes'
      - 'namespaces'
    verbs:
      - '*'
  - apiGroups:
      - 'iam.kubesphere.io'
    resources:
      - 'roles'
      - 'members'
      - 'members/nodegrouproles'
    verbs:
      - '*'
  - apiGroups:
      - 'resources.kubesphere.io'
    resources:
      - 'namespaces'
      - 'services'
    verbs:
      - '*'

---
apiVersion: iam.kubesphere.io/v1alpha2
kind: RoleBase
metadata:
  name: nodegroup-viewer
role:
  apiVersion: iam.kubesphere.io/v1alpha2
  kind: NodeGroupRole
  metadata:
    annotations:
      iam.kubesphere.io/aggregation-roles: '["role-template-view-nodegroups"]'
      kubesphere.io/creator: system
    name: viewer
  rules:
    - apiGroups:
        - 'infra.kubesphere.io'
      resources:
        - 'nodegroups'
        - 'nodes'
        - 'namespaces'
      verbs:
        - 'get'
        - 'list'
        - 'watch'
    - apiGroups:
        - 'resources.kubesphere.io'
      resources:
        - 'namespaces'
        - 'services'
      verbs:
        - 'get'
        - 'list'
        - 'watch'

---
apiVersion: iam.kubesphere.io/v1alpha2
kind: RoleBase
metadata:
  name: nodegroup-admin
role:
  apiVersion: iam.kubesphere.io/v1alpha2
  kind: NodeGroupRole
  metadata:
    annotations:
      iam.kubesphere.io/aggregation-roles: '["role-template-manage-nodegroups","role-template-view-nodegroups"]'
      kubesphere.io/creator: system
    name: admin
  rules:
    - apiGroups:
        - 'infra.kubesphere.io'
      resources:
        - 'nodegroups'
        - 'nodes'
        - 'namespaces'
      verbs:
        - '*'
    - apiGroups:
        - 'iam.kubesphere.io'
      resources:
        - 'roles'
        - 'members'
        - 'members/nodegrouproles'
      verbs:
        - '*'
    - apiGroups:
        - 'resources.kubesphere.io'
      resources:
        - 'namespaces'
        - 'services'
      verbs:
        - '*'