# Default values for whizard-edge-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#global:
#  imageRegistry: registry.cn-beijing.aliyuncs.com
#  tag: v0.1.0
#  imagePullSecrets: []

whizard_agent_proxy:
  image:
    repository: kubesphere/whizard-monitoring-agent-proxy
    tag: "v0.8.0"
    digest: ""
    pullPolicy: IfNotPresent
  tenant: ""
  gateway_address: ""

whizard_edge_proxy:
  image:
    repository: kubesphere/whizard-edge-proxy
    tag: "v0.3.4"
    digest: ""
    pullPolicy: IfNotPresent
  tenant: ""
  edge_gateway_address: ""
  chrony_port: ""
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

prometheus:
  image:
    repository: prom/prometheus
    pullPolicy: IfNotPresent
    tag: v2.39.1
  storage:
    className: ""
    prometheus_pv_size: ""

prometheusOperator:
  image:
    repository: kubesphere/prometheus-operator
    pullPolicy: IfNotPresent
    tag: v0.55.1

  reloaderImage:
    repository: kubesphere/prometheus-config-reloader
    pullPolicy: IfNotPresent
    tag: v0.55.1

npu_exporter:
  image:
    repository: kubesphere/npu-exporter
    pullPolicy: IfNotPresent
    tag: v3.0.0

dcgm_exporter:
  image:
    repository: kubesphere/dcgm-exporter
    pullPolicy: IfNotPresent
    tag: 3.1.7-3.1.4-ubuntu20.04

  podSecurityContext: {}

  tolerations:
    - key: node-role.kubernetes.io/edge
      operator: Exists
      effect: NoSchedule

  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    capabilities:
      add: [ "SYS_ADMIN" ]

  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # Comment the following line to stop profiling metrics from DCGM
  arguments: [ "-f", "/etc/dcgm-exporter/dcp-metrics-included.csv" ]

kubeStateMetrics:
  image:
    repository: kubesphere/kube-state-metrics
    pullPolicy: IfNotPresent
    tag: v2.6.0

kubeRBACProxy:
  image:
    repository: kubesphere/kube-rbac-proxy
    pullPolicy: IfNotPresent
    tag: v0.11.0

nodeExporter:
  image:
    repository: prom/node-exporter
    pullPolicy: IfNotPresent
    tag: v1.3.1

defaultImageRegistry: ""
edgeImageRegistry: ""
imagePullSecrets:
- name: "abc"
clusterType: "auto"
