# Default values for whizard-edge-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#global:
#  imageRegistry: registry.cn-beijing.aliyuncs.com
#  tag: v0.1.0
#  imagePullSecrets: []

whizard_agent_proxy:
  image:
    repository: kubesphere/whizard-monitoring-agent-proxy
    tag: "v0.5.0"
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  tenant: ""
  gateway_address: ""

# Config for PrometheusAgent in EdgeCluster
prometheus:
  nodePort: 30991

defaultImageRegistry: ""
