# Default values for whizard-edge-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#global:
#  imageRegistry: registry.cn-beijing.aliyuncs.com
#  tag: v0.1.0
#  imagePullSecrets: []

whizard_agent_proxy:
  image:
    repository: kubesphere/whizard-monitoring-agent-proxy
    tag: "v0.6.2"
    digest: ""
    pullPolicy: IfNotPresent
  tenant: ""
  gateway_address: ""

whizard_edge_agent_proxy:
  image:
    repository: frezes/whizard-edge-agent-proxy
    tag: "v0.1.0"
    digest: ""
    pullPolicy: IfNotPresent

edge_agent:
  nodePort:

prometheus:
  storage:
    className: ""
    prometheus_pv_size: ""

defaultImageRegistry: ""
#imagePullSecrets:
