{{- if .Values.fluentbit.kubeedge.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluentbit-edge-kylin-v10
  namespace: fluent
  labels:
    app.kubernetes.io/name: fluent-bit-edge-kylin-v10
spec:
  image: {{ include "fluent-operator.kylinEdgeImage" (dict "global" .Values "imageInfo" .Values.fluentbit.image) }}
  {{- if .Values.fluentbit.imagePullSecrets }}
  imagePullSecrets:
  {{- toYaml .Values.fluentbit.imagePullSecrets | nindent 8 }}
  {{- end }}
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/edge/
  resources:
{{- toYaml .Values.fluentbit.resources | nindent 4  }}
  fluentBitConfigName: fluent-bit-config-edge
  tolerations:
    - key: node-role.kubernetes.io/edge
      operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: accelerator
            operator: DoesNotExist
          - key: kylin-v10
            operator: Exists
          - key: nvidia.com/gpu.present
            operator: DoesNotExist
          - key: node-role.kubernetes.io/edge
            operator: Exists
          - key: vcluster.loft.sh/fake-node
            operator: DoesNotExist
  hostNetwork : true
  volumes:
    - name: host-proc
      hostPath:
        path: /proc/
    - name: host-sys
      hostPath:
        path: /sys/
    - name: host-kubeedge
      hostPath:
        path: /etc/kubeedge/
  volumesMounts:
    - mountPath: /host/sys
      mountPropagation: HostToContainer
      name: host-sys
      readOnly: true
    - mountPath: /host/proc
      mountPropagation: HostToContainer
      name: host-proc
      readOnly: true
    - mountPath: /etc/kubeedge
      mountPropagation: HostToContainer
      name: host-kubeedge
      readOnly: true
{{- end }}