{{- if .Values.fluentbit.kubeedge.enable -}}
{{- if .Values.fluentbit.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: edge-tail
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
    node-role.kubernetes.io/edge: "true"
    node-role.kubernetes.io/gpu: "true"
    node-role.kubernetes.io/npu: "true"
spec:
  match: kube.*
  filters:
    - lua:
        script:
          key: edge-tail.lua
          name: fluent-bit-edge-tail-lua
        call: extract_metadata
        timeAsTable: true
{{- end }}
{{- end }}
