{{- if .Values.fluentbit.kubeedge.enable -}}
{{- if .Values.fluentbit.enable -}}
{{- if .Values.fluentbit.input.tail.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: edge-tail
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
    node-role.kubernetes.io/edge: "true"
    node-role.kubernetes.io/gpu: "true"
    node-role.kubernetes.io/npu: "true"
spec:
  tail:
    tag: kube.<namespace_name>.<pod_name>.<container_name>
    tagRegex: (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
    path: {{ .Values.fluentbit.input.tail.path }}
    readFromHead: {{ .Values.fluentbit.input.tail.readFromHead }}
    {{- if eq .Values.containerRuntime "docker" }}
    parser: docker
    {{- else if eq .Values.containerRuntime "containerd" }}
    parser: cri
    {{- else if eq .Values.containerRuntime "crio" }}
    parser: cri
    {{- end }}
    refreshIntervalSeconds: {{ .Values.fluentbit.input.tail.refreshIntervalSeconds }}
    memBufLimit: {{ .Values.fluentbit.input.tail.memBufLimit }}
    skipLongLines: {{ .Values.fluentbit.input.tail.skipLongLines }}
    db: /fluent-bit/tail/pos.db
    dbSync: Normal
    storageType: {{ .Values.fluentbit.input.tail.storageType }}
    {{- if eq .Values.fluentbit.input.tail.storageType "filesystem" }}
    pauseOnChunksOverlimit: {{ .Values.fluentbit.input.tail.pauseOnChunksOverlimit | quote }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
