{{- if .Values.fluentbit.kubeedge.enable -}}
{{- if .Values.fluentbit.enable -}}
{{- if .Values.fluentbit.input.systemd.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: {{ .Values.containerRuntime }}-edge
  labels:
    fluentbit.fluent.io/enabled: "true"
    node-role.kubernetes.io/edge: "true"
    node-role.kubernetes.io/gpu: "true"
    node-role.kubernetes.io/npu: "true"
spec:
  systemd:
    tag: service.*
    path: {{ .Values.fluentbit.input.systemd.path }}
    db: /fluent-bit/tail/systemd.db
    dbSync: Normal
    stripUnderscores: {{ .Values.fluentbit.input.systemd.stripUnderscores | quote }}
    systemdFilter:
{{- if .Values.fluentbit.input.systemd.systemdFilter.enable }}
      - _SYSTEMD_UNIT={{ .Values.containerRuntime }}.service
      {{- if .Values.fluentbit.input.systemd.includeKubelet }}
      - _SYSTEMD_UNIT=edgecore.service
      {{- end }}
      {{- if .Values.fluentbit.input.systemd.systemdFilter.filters }}
{{- toYaml .Values.fluentbit.input.systemd.systemdFilter.filters | nindent 6 }}
      {{- end }}
{{- end }}
    storageType: {{ .Values.fluentbit.input.systemd.storageType }}
   {{- if eq .Values.fluentbit.input.systemd.storageType "filesystem" }}
    pauseOnChunksOverlimit: {{ .Values.fluentbit.input.systemd.pauseOnChunksOverlimit | quote }}
   {{- end }}
{{- end }}
{{- end }}
{{- end }}
