{{- if .Values.fluentbit.kubeedge.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: prometheus-remote-write-edge
  labels:
    fluentbit.fluent.io/enabled: "true"
    node-role.kubernetes.io/edge: "true"
spec:
  match: kubeedge.metrics.*
  prometheusRemoteWrite:
    host: {{ .Values.fluentbit.kubeedge.prometheusRemoteWrite.host }}
    port: {{ .Values.fluentbit.kubeedge.prometheusRemoteWrite.port }}
    uri: /push/{{ .Values.fluentbit.kubeedge.prometheusRemoteWrite.routerKey }}
    {{- if .Values.fluentbit.kubeedge.prometheusRemoteWrite.tlsEnable }}
    tls:
      verify: true
      caFile: /etc/kubeedge/ca/rootCA.crt
      crtFile: /etc/kubeedge/certs/server.crt
      keyFile: /etc/kubeedge/certs/server.key
    {{- end }}
    addLabels : 
      app : fluentbit
      node: ${NODE_NAME}
      job : kubeedge
{{- end }}