{{- if .Values.fluentbit.kubeedge.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: nvidia-gpu-exporter-metrics-edge
  labels:
    fluentbit.fluent.io/enabled: "true"
    node-role.kubernetes.io/gpu: "true"
spec:
  prometheusScrapeMetrics:
    tag: kubeedge.*
    host: 127.0.0.1
    port: 9400
    scrapeInterval: 30s
    metricsPath : /metrics
{{- end }}