{{- if .Values.fluentbit.kubeedge.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-edge-tail-lua
data:
  edge-tail.lua: |
    function extract_metadata(tag, timestamp, record)
      local delimiter = "."
      local find, sub, insert = string.find, string.sub, table.insert
      local res = {}
      local start, start_pos, end_pos = 1, 1, 1
      while true do
        start_pos, end_pos = find(tag, delimiter, start, true)
        if not start_pos then
          break
        end
        insert(res, sub(tag, start, start_pos - 1))
        start = end_pos + 1
      end
      insert(res, sub(tag,start))

      new_record = {}
      kubernetes = {}
      kubernetes["namespace_name"] = res[2]
      kubernetes["pod_name"] = res[3]
      kubernetes["container_name"] = res[4]
      new_record["kubernetes"] = kubernetes


      timeStr = os.date("!*t", timestamp["sec"])
      t = string.format("%4d-%02d-%02dT%02d:%02d:%02d.%sZ",
      timeStr["year"], timeStr["month"], timeStr["day"],
      timeStr["hour"], timeStr["min"], timeStr["sec"],
      timestamp["nsec"])

      new_record["time"] = t
      {{- if eq .Values.containerRuntime "docker" }}
      new_record["log"] = record["log"]
      {{- else }}
      new_record["log"] = record["message"]
      {{- end }}

      return 1, timestamp, new_record
    end
{{- end }}