apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: edge-ota-server
  name: edge-ota-server-sa
  namespace: kubeedge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-ota-server
  labels:
    kubeedge: edge-ota-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edge-ota-server
subjects:
- kind: ServiceAccount
  name: edge-ota-server-sa
  namespace: kubeedge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-ota-server
  labels:
    k8s-app: kubeedge
    kubeedge: edge-ota-server
rules:
- apiGroups: [""]
  resources: ["nodes","configmaps","secrets","services"]
  verbs: ["get", "list", "watch","delete"]
