---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: edge-ota-server
  name: edge-ota-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-ota-server
  template:
    metadata:
      labels:
        app: edge-ota-server
    spec:
      serviceAccount: edge-ota-server-sa
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - command:
        - edge-ota-server
        image: {{ .Values.defaultImageRegistry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: edge-ota-server
        env:
          - name: OTA_PORT
            value: {{ .Values.gateway.nodePort.otaPort | quote }}
          - name: CHRONY_PORT
            value: {{ .Values.gateway.nodePort.chronyPort | quote }}
          {{- if .Values.gateway.advertiseAddress }}
          - name: ADVERTISE_ADDRESS
            value: {{ index .Values.gateway.advertiseAddress 0 | quote }}
          {{- end }}
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 500Mi
      restartPolicy: Always