apiVersion: v1
kind: Service
metadata:
  labels:
    app: edge-ota-server
  name: edge-ota-server
  namespace: kubeedge
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
    nodePort: 30088
  selector:
    app: edge-ota-server
  type: NodePort
