---
# Source: dcgm-exporter/templates/daemonset.yaml
# Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcgm-exporter
  namespace: kubesphere-monitoring-system
  labels:
    app.kubernetes.io/version: "3.1.7"
    app.kubernetes.io/component: "dcgm-exporter"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/version: "3.1.7"
      app.kubernetes.io/component: "dcgm-exporter"
  template:
    metadata:
      labels:
        app.kubernetes.io/version: "3.1.7"
        app.kubernetes.io/component: "dcgm-exporter"
    spec:
      priorityClassName: system-node-critical
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- if .Values.dcgm_exporter.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.dcgm_exporter.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.dcgm_exporter.affinity }}
      affinity:
        {{- toYaml .Values.dcgm_exporter.affinity | nindent 8 }}
      {{- end }}
      {{- with .Values.dcgm_exporter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - name: "pod-gpu-resources"
        hostPath:
          path: /var/lib/kubelet/pod-resources
      - configMap:
          name: exporter-metrics-config-map
        name: exporter-metrics-volume
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: exporter
        securityContext:
          {{- toYaml .Values.dcgm_exporter.securityContext | nindent 10 }}
        image: "{{ .Values.defaultImageRegistry }}{{ .Values.dcgm_exporter.image.repository }}:{{ .Values.dcgm_exporter.image.tag }}"
        imagePullPolicy: "{{ .Values.dcgm_exporter.image.pullPolicy }}"
        args:
        - -f
        - "/etc/dcgm-exporter/dcp-metrics-included.csv"
        env:
        - name: "DCGM_EXPORTER_KUBERNETES"
          value: "true"
        - name: "DCGM_EXPORTER_LISTEN"
          value: ":9400"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: "metrics"
          containerPort: 9400
        volumeMounts:
        - name: "pod-gpu-resources"
          readOnly: true
          mountPath: "/var/lib/kubelet/pod-resources"
        - name: exporter-metrics-volume
          mountPath: /etc/dcgm-exporter
        livenessProbe:
          httpGet:
            path: /health
            port: 9400
          initialDelaySeconds: 45
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 9400
          initialDelaySeconds: 45
        {{- if .Values.dcgm_exporter.resources }}
        resources:
          {{- toYaml .Values.dcgm_exporter.resources | nindent 10 }}
        {{- end }}
