apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/created-by: edgewize.io/edgewize-apiserver
  labels:
    app: edgewize-apiserver
    tier: backend
    version: {{ .Chart.AppVersion }}
  name: edgewize-apiserver
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
    {{- with .Values.apiserver.nodePort }}
      nodePort:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  selector:
    app: edgewize
    tier: backend
    # version: {{ .Chart.AppVersion }}
{{- if .Values.apiserver.nodePort }}
  type: NodePort
{{- else}}
  type: ClusterIP
{{- end}}
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: edgewize-controller-manager
    tier: backend
    version: {{ .Chart.AppVersion }}
  name: edgewize-controller-manager
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: edgewize
    tier: backend
    # version: {{ .Chart.AppVersion }}
  sessionAffinity: None
  type: ClusterIP
