name: BuildNightlyContainerImage

on:
    schedule:
      # This is a UTC time
      - cron: "0 17 * * *"
    # Keep it only for test purpose, comment it once everything is ok
    workflow_dispatch:

env:
  # TODO: Change variable to your image's repo.
  IMAGE_REPO: ${{ vars.IMAGE_REPO }}
  IMAGE_VERSION: latest
  
jobs:
  build:
    name: Build
    runs-on: self-hosted
    # TODO: Change variable to your repo's name.
    if: github.repository	== 'edgewize-io/edgewize-ee'

    steps: 
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: edgewize-kse-4.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
          tag=nightly-$(date '+%Y%m%d')
          REPO=edgewize TAG=${tag} make container-cross-push    
